language: java

sudo: false

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

cache:
  directories:
    - $HOME/.m2
    
env:
  global:
    - MAVEN_OPTS="-Xms4g -Xmx4g"
    - JAVA_OPTS="-Xms4g -Xmx4g"

script: mvn clean install 