language: java

sudo: false

services:
  - docker

cache:
  directories:
    - $HOME/.m2
    
env:
  global:
    - MAVEN_OPTS="-Xms4g -Xmx4g"
    - JAVA_OPTS="-Xms4g -Xmx4g"

script: 
 - docker build -t helenus .
 - docker run -it -v $(pwd):/root/sources -w /root/sources helenus mvn clean install